### ISSUE TITLE
Push to Docker, etc

### ISSUE THREAD

**Issue by joshgoebel** [exercism/wren-test-runner#2]
Can the GitHub action simply be copied from https://github.com/exercism/ruby-test-runner/blob/main/.github/workflows/docker.yml ?

Do any secrets need to be added to this repo or are they organizational?

**Comment by iHiD** [comment]
1. Copy the deploy files. Probably csharp-test-runner is the safest up-to-date one.
2. I've added the secrets
3. Erik needs to manually make the first push to DockerHub
4. When you're ready, you need to copy this PR for wren: https://github.com/exercism/terraform/pull/44/files

**Comment by joshgoebel** [comment]
@ErikSchierboom I split the Docker stuff out into #4 (copied docker.yml from `sharp-test-runner`).  If it looks good we can merge and that should free you up to do the first manual push to Dockerhub.

**Comment by ErikSchierboom** [comment]
@joshgoebel I've approved #4. Once that is merged, I'll do the first manual push to Dockerhub.

**Comment by joshgoebel** [comment]
Merged.

**Comment by ErikSchierboom** [comment]
@joshgoebel I've done the initial Docker hub push. If you do a terraform PR, then the Docker workflow should be green.

**Comment by joshgoebel** [comment]
I'm confused about sequencing... should I go ahead and make a terraform PR now then?

**Comment by ErikSchierboom** [comment]
@joshgoebel Yes please!

**Comment by joshgoebel** [comment]
Let me know when I should bee able to test the test runner on `exercism.lol` :-)

**Comment by ErikSchierboom** [comment]
@joshgoebel The terraform PR must have been merged and Jeremy must have run the terraform deploy script. Once he's done that, you should re-run the `docker` workflow which then pushes the Docker images to the right locations.
